version: "3"

services:
  server:
    build: ./server
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ../:/go/src/github/igm50/portfolio-react

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: database
            port: 3306
            user: root
            password: prisma

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

  schema-applicant:
    build: ./schema-applicant
    tty: true
    volumes:
      - ../prisma:/usr/src/app

volumes:
  mysql: ~
