@startuml

title 型定義

package identity {
  class "人物" as Person {
    id: string
    name: string
    mailAddress: string
    blogs: [Blog]
    languages: [Language]
  }

  class "ブログ" as Blog {
    id: string
    url: string
    name: string
  }
}

package language {
  class "言語" as Language {
    id: string
    name: string
    libraries: [Library]
    versions: [float]
  }

  class "ライブラリ" as Library {
    id: string
    name: string
    versions: [float]
  }
}

Person --> Blog
Person -right-> Language
Language --> Library

@enduml
